// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwlob54PmEYiwygvVk1NWfxI9dh5rpywk',
    appId: '1:863996752325:web:dca72d100132dbe6d41bac',
    messagingSenderId: '863996752325',
    projectId: 'neusocial-81448',
    authDomain: 'neusocial-81448.firebaseapp.com',
    storageBucket: 'neusocial-81448.appspot.com',
    measurementId: 'G-QP2GJQ4MZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw58BB5tvxkHB8bKipBm40WZAs64eUxQk',
    appId: '1:863996752325:android:5bc4223d56a773f1d41bac',
    messagingSenderId: '863996752325',
    projectId: 'neusocial-81448',
    storageBucket: 'neusocial-81448.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH2qxME3Qj3GHfgag2F177SSy8VuQac6s',
    appId: '1:863996752325:ios:9846fc53b4ada46ed41bac',
    messagingSenderId: '863996752325',
    projectId: 'neusocial-81448',
    storageBucket: 'neusocial-81448.appspot.com',
    iosBundleId: 'com.example.nueusocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH2qxME3Qj3GHfgag2F177SSy8VuQac6s',
    appId: '1:863996752325:ios:9846fc53b4ada46ed41bac',
    messagingSenderId: '863996752325',
    projectId: 'neusocial-81448',
    storageBucket: 'neusocial-81448.appspot.com',
    iosBundleId: 'com.example.nueusocial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwlob54PmEYiwygvVk1NWfxI9dh5rpywk',
    appId: '1:863996752325:web:93c3b6cdc522ef56d41bac',
    messagingSenderId: '863996752325',
    projectId: 'neusocial-81448',
    authDomain: 'neusocial-81448.firebaseapp.com',
    storageBucket: 'neusocial-81448.appspot.com',
    measurementId: 'G-FMLYQ0MC2F',
  );
}
